version: "3.9"

networks:
  cirilofood-network:
    driver: bridge

services:
  cirilofood-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
    ports:
      - "3306:3306"
    networks:
      - cirilofood-network

  cirilofood-api:
    #build: . //uses Dockerfile to build
    #image: cmcirilo/cirilofood-api
    image: cirilofood-api
    command: ["/wait-for-it.sh", "cirilofood-mysql:3306", "-t", "30", "--", "java", "-jar", "api.jar"]
    environment:
      DB_HOST: cirilofood-mysql
#    ports:
#      - "8080:8080"
    networks:
      - cirilofood-network
    depends_on:
      - cirilofood-mysql
#    deploy:
#      replicas: 2

#starts
#docker-compose up

#starts with multiple containers
#docker-compose up --scale cirilofood-api=2

#stops
#docker-compose down --volumes
