#Database
#spring.datasource.username=
#spring.datasource.password=

#Sprint Session (Redis)
spring.session.store-type=redis
#spring.redis.host=
#spring.redis.port=
#spring.redis.password=

#Logging
#logging.loggly.token=

#Security
cirilofood.jwt.keystore.jks-location=
cirilofood.jwt.keystore.password=
cirilofood.jwt.keystore.keypair-alias=

#Storage
cirilofood.storage.type=s3
cirilofood.storage.s3.photos-folder=photos
#cirilofood.storage.s3.access-key-id=
#cirilofood.storage.s3.access-key-secret=
#cirilofood.storage.s3.bucket=
#cirilofood.storage.s3.region=

#Mail
cirilofood.mail.impl=smtp
#cirilofood.mail.sender=
#spring.mail.host=smtp.sendgrid.net
#spring.mail.port=587
#spring.mail.username=apikey
#spring.mail.password=




